apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: banking
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: backend
  selector:
    app: backend-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deployment
  name: backend-deployment
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - image: localhost:5001/banking-api:latest
        imagePullPolicy: Never
        name: banking-api
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
